name: Generate Coverage
on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      
      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          run_install: false
      
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      
      - uses: pnpm/action-setup@v2.2.2
        with:
          run_install: true

      - name: Build packages
        run: pnpm run build
      
      - name: Generate coverage report
        run: pnpm run coverage --no-threads
      
      - name: Upload imagetools-core Report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: imagetools-core
          files: 'packages/core/coverage/coverage-final.json'
      
      - name: Upload vite-imagetools Report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: vite-imagetools
          files: 'packages/vite/coverage/coverage-final.json'
      
      - name: Upload rollup-plugin-imagetools Report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: rollup-plugin-imagetools
          files: 'packages/rollup/coverage/coverage-final.json'
