name: Generate Coverage
on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.2.2
        with:
          run_install: true
      - name: Build packages
        run: pnpm run build
      - name: Generate coverage report
        run: pnpm run coverage
      - name: Upload imagetools-core Report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: imagetools-core
          files: 'packages/core/coverage/coverage-final.json'

      - name: Upload vite-imagetools Report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: vite-imagetools
          files: 'packages/vite/coverage/coverage-final.json'

      - name: Upload rollup-plugin-imagetools Report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: rollup-plugin-imagetools
          files: 'packages/rollup/coverage/coverage-final.json'
